[build]
builder = "nixpacks"

[build.nixpacksVersion]
node = "22"

[build.nixpacksBuildCommand]
cmd = "yarn workspace finance-tracker-backend build"

[deploy]
startCommand = "yarn workspace finance-tracker-backend start"